#!/bin/sh

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/bar_colors"

#set initial volume

volStatus=$(amixer get Master | tail -n 1 | cut -d '[' -f 4 | sed 's/].*//g')
volLevel=$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | sed 's/%.*//g')

# is alsa muted or not muted?
if [ "$volStatus" == "on" ]
then
	snd="%{A:amixer sset Master toggle:}%{B$GREEN}%{F$BCOLOR} VOL:$volLevel %{F-}%{B-}%{A}"
else
	# If it is muted, make the font red
	snd="%{A:amixer sset Master toggle:}%{F$GREEN} VOL:$volLevel %{F-}%{A}"
fi

while read -r line ; do 
	case $line in
		T*)
			#xtitle
			title="${line#?}"
			;;
		C*)
			#clock and system
			sys="%{F$FCOLOR}%{B$BCOLOR} ${line#?} %{B-}%{F-}"
			;;

		N*)
		    #wifi ssid
			wifi="${line#?}"
			;;
		
		c*)
				#sound status
					    
			volStatus=$(amixer get Master | tail -n 1 | cut -d '[' -f 4 | sed 's/].*//g')
			volLevel=$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | sed 's/%.*//g')
			# is alsa muted or not muted?
			if [ "$volStatus" == "on" ]
			then
					snd="%{A:amixer sset Master toggle:}%{A4:amixer sset Master 5+:}%{A5:amixer sset Master 5-:}%{B$GREEN}%{F$BCOLOR} VOL:$volLevel %{F-}%{B-}%{A}%{A}%{A}"
			else
					# If it is muted, make the font red
					snd="%{A:amixer sset Master toggle:}%{F$GREEN} VOL:$volLevel %{F-}%{A}"
			fi
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								BG=$COLOR_FOCUSED_OCCUPIED_BG
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								BG=$COLOR_FOCUSED_URGENT_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} # %{A}%{B-}%{F-}"
						;;
#					[LTG]*)
						# layout, state and flags
#						wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
#						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm} ${wifi} %{c}${title} %{r} ${snd}${sys}"
done
