#!/bin/sh

HEIGHT=25
BAR_FIFO=/tmp/bar-fifo
BAR_FONT="GohuFont:size=8"
BAR_WM_NAME=bspwm_bar
export BAR_FIFO HEIGHT PANEL_FONT BAR_WM_NAME

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/bar_colors"


if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bar_volume() {
	volStatus=$(amixer get Master | tail -n 1 | cut -d '[' -f 4 | sed 's/].*//g')
    volLevel=$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | sed 's/%.*//g')
    # is alsa muted or not muted?
    if [ "$volStatus" == "on" ]
    then
            echo "%{A:amixer sset Master toggle:}%{B$GREEN}%{F$BCOLOR} VOL:$volLevel %{F-}%{B-}%{A}"
    else
            # If it is muted, make the font red
            echo "%{A:amixer sset Master toggle:}%{F$GREEN} VOL:$volLevel %{F-}%{A}"
    fi
}

bar_ram() {
	freeram=$(awk '/MemTotal:/{total=$2}/MemAvailable:/{free=$2;print int((total/free))}' /proc/meminfo)
	

	echo "%{F$BLUE} RAM:$freeram %{F-}"
	}

bar_cpu() {
	CPU=$(printf "%.0f\n" $(ps -eo pcpu | awk 'BEGIN {sum=0.0f} {sum+=$1} END {print sum/4}'))

	if [ "$CPU" -lt 10 ]
	then
		echo "%{A:urxvt -e htop:}%{F$BLUE} CPU:$CPU %{F-}%{A}"
	elif [ "$CPU" -lt 50 ]
	then
		echo "%{A:urxvt -e htop:}%{F$PURPLE} CPU:$CPU %{F-}%{A}"
	else
		echo "%{A:urxvt -e htop:}%{F$PINK} CPU:$CPU %{F-}%{A}"
	fi
}

bar_bat() {
	BAT=$(acpi | cut -d ' ' -f 4 | cut -c 1-2)
	STAT=$(acpi | cut -d ' ' -f 3)

	if [ "$STAT" == "Charging," ]
	then
		echo "%{B$TEAL}%{F$BCOLOR} BAT:$BAT %{F-}%{B-}"
	elif [ "$BAT" -lt 25 ]
	then
		echo "%{F$BCOLOR}%{B$RED} BAT:$BAT %{F-}%{B-}"
	elif [ "$BAT" -lt 40 ]
	then
		echo "%{F$ORANGE} BAT:$BAT%{F-}"
	elif [ "$BAT" -lt 60 ]
	then
		echo "%{F$YELLOW} BAT:$BAT%{F-}"
	else
		echo "%{F$GREEN} BAT:$BAT%{F-}"
	fi
}

bar_wifi() {
		WIFI=$(iwconfig wlp3s0 | grep ESSID | cut -d ':' -f 2 | cut -d \" -f 2)
		SIG=$(iwconfig wlp3s0 | grep Quality | cut -d '=' -f 2 | cut -d '/' -f 1)

		if [ "$SIG" == "" ]
		then 
				echo "%{B$YELLOW}%{F$BCOLOR} No wifi %{F-}%{B-}"
		elif [ "$SIG" -lt 35 ]
		then
				echo "%{F$RED}$WIFI %{F-}"
		elif [ "$SIG" -lt 60 ]
		then
				echo "%{F$ORANGE}$WIFI %{F-}"
		else
				echo "%{F$PURPLE}$WIFI %{F-}"
		fi
}

[ -e "$BAR_FIFO" ] && rm "$BAR_FIFO"
mkfifo "$BAR_FIFO"

bspc config top_padding $HEIGHT
bspc subscribe report > "$BAR_FIFO" &
stdbuf -oL alsactl monitor > "$BAR_FIFO" &
xtitle -sf 'T%s' > "$BAR_FIFO" &
"$DIR/bar_format" < "$BAR_FIFO" | lemonbar -n "$BAR_WM_NAME" -p -g 1366x25 -F "$FCOLOR" -B "$BCOLOR" -f "$BAR_FONT" | sh >> /home/taate/scripts/barlog &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

while true; do
	echo "N" "$(bar_wifi)" > "$BAR_FIFO"
	echo "C" "$(bar_cpu)""$(bar_ram)""$(bar_bat)"" $(date "+%d.%m %H:%M") " > "$BAR_FIFO"
	sleep 5s
done &

wait
