#!/bin/sh

HEIGHT=20
BAR_FIFO=/tmp/bar-fifo
BAR_FONT="GohuFont:size=8"
BAR_WM_NAME=bspwm_bar
export BAR_FIFO HEIGHT PANEL_FONT BAR_WM_NAME

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/bar_colors"


if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bar_ram() {
	freeram=$(awk '/MemTotal:/{total=$2}/MemAvailable:/{free=$2;print int((total/free))}' /proc/meminfo)
	

	echo "%{F$BLUE} RAM:$freeram %{F-}"
	}

bar_cpu() {
	CPU=$(printf "%.0f\n" $(ps -eo pcpu | awk 'BEGIN {sum=0.0f} {sum+=$1} END {print sum/4}'))

	if [ "$CPU" -lt 10 ]
	then
		echo "%{A:urxvt -e htop &:}%{F$BLUE} CPU:$CPU %{F-}%{A}"
	elif [ "$CPU" -lt 50 ]
	then
		echo "%{A:urxvt -e htop &:}%{F$PURPLE} CPU:$CPU %{F-}%{A}"
	else
		echo "%{A:urxvt -e htop &:}%{B$PINK}%{F$BCOLOR} CPU:$CPU %{F-}%{B-}%{A}"
	fi
}

[ -e "$BAR_FIFO" ] && rm "$BAR_FIFO"
mkfifo "$BAR_FIFO"

bspc config top_padding $HEIGHT
bspc subscribe report > "$BAR_FIFO" &
stdbuf -oL alsactl monitor > "$BAR_FIFO" &
xtitle -sf 'T%s' > "$BAR_FIFO" &
"$DIR/bar_format" < "$BAR_FIFO" | lemonbar -n "$BAR_WM_NAME" -p -g 1920x20 -F "$FCOLOR" -B "$BCOLOR" -f "$BAR_FONT" | sh >> /home/taate/scripts/barlog &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

while true; do
	echo "C" "$(bar_cpu)""$(bar_ram)"" ""$(date "+%d.%m %H:%M")"" " > "$BAR_FIFO"
	sleep 5s
done &

wait
