#! /bin/sh

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

screen1=$(xrandr | grep " connected " | awk '{ print$1 }')

if "$screen1" == "eDP"; then
	xrandr --output eDP --mode 1920x1080 --rotate normal --output HDMI-A-0 --off
elif "$screen1" == "HDMI-0"; then
	xrandr --output DisplayPort-0 --off --output HDMI-0 --mode 2560x1440 --pos 0x0 --rotate normal --output DVI-0 --off
fi

wal --theme random -o "${HOME}/git/dotfiles/.config/wal/postwal.sh"
xsetroot -cursor_name left_ptr &

dunst &
telegram-desktop &
polybar spacebar &
redshift 63.11:24.49 &
udiskie &
setxkbmap fi &
cadence &
syncthing-gtk &
sxhkd &
picom &
steam-native &
discord &

$HOME/.config/nvim/bspwm_border_color/listener &
$HOME/capsdisable.sh &

bspc monitor $screen1 -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap          20
bspc config top_padding			25
bspc config single_monocle		false

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config auto_cancel true

bspc rule -a vlc sticky=on state='pseudo_tiled'

