#! /bin/sh

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

xrandr --output eDP --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI-A-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DisplayPort-0 --off --output DisplayPort-1 --off

wal --theme random -o "${HOME}/git/dotfiles/.config/wal/postwal.sh"
xsetroot -cursor_name left_ptr &

dunst &
telegram-desktop &
polybar spacebar &
redshift 63.11:24.49 &
udiskie &
setxkbmap fi &
syncthing-gtk &
sxhkd &
picom &
setxkbmap fi &
$HOME/.config/nvim/bspwm_border_color/listener &
$HOME/capsdisable.sh &

bspc monitor 0x00600004 -d 1 2 3 4 5
bspc monitor 0x00600002 -d 6 7

bspc config border_width         3
bspc config window_gap          20
bspc config top_padding			25
bspc config single_monocle		false

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config auto_cancel true

bspc rule -a vlc sticky=on state='pseudo_tiled'

