#! /bin/sh

setxkbmap fi &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
telegram-desktop &
st -c "Mutt" mutt &
polybar spacebar &
redshift 63.09:21.61 &
steam-native &
sxhkd &

bspc monitor -d 1 2 3 4 5 T N S

bspc config border_width         2
bspc config window_gap          20
bspc config top_padding			25
bspc config single_monocle		true

bspc config normal_border_color \#3b3228 
bspc config presel_feedback_color \#7e705a
bspc config focused_border_color \#d0c8c6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config auto_cancel true

bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a vlc sticky=on state='pseudo_tiled'
bspc rule -a 'Mutt' desktop='^7'
bspc rule -a 'Steam' desktop='^8'

